parameters:
    rapl.configuration.class: RAPL\RAPL\Configuration
    rapl.entity_manager.class: RAPL\RAPL\EntityManager

services:
#    rapl.example:
#        class: %rapl.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
